### ISSUE TITLE
Custom collection format: define name of the images

### ISSUE THREAD

**Issue by hagc** [appelmar/gdalcubes_R#19]
After issue #8, I tried to make a custom collection format, but not for original data downloaded from the internet, but a dataset created by me.
Now the image collection created with `create_image_collection` looks like this:

> A GDAL image collection object, referencing 5 images with 4  bands
Images:
             name      left      top   bottom     right            datetime                                                srs
1 20171002-113001 -10.15275 38.84894 37.85395 -8.887526 2017-10-02T11:30:01 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
2 20171005-113316 -10.15275 38.84894 37.85395 -8.887526 2017-10-05T11:33:16 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
3 20171005-114043 -10.15275 38.84894 37.85395 -8.887526 2017-10-05T11:40:43 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
4 20171012-112713 -10.15275 38.84894 37.85395 -8.887526 2017-10-12T11:27:13 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
5 20171015-113318 -10.15275 38.84894 37.85395 -8.887526 2017-10-15T11:33:18 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 

> 
> Bands:
>            name offset scale unit nodata image_count
> 1 MultiSpectral      0     1                       5
> 2          NDMI      0     1                       5

The problem is that the name of the images (Sentinel) are defined as e.g. "20171002-113001". Then, when I add another image acquired at same time and hour from an adjacent tile, function `create_image_collection` fails with the error

`Error in libgdalcubes_create_image_collection(files, format, out_file,  : 
  ERROR in image_collection::add(): cannot add dataset to gdalrefs table.`

I guess the problem is that two different images (from different tiles) would get the same name (e.g. "20171002-113001"). So I guess that adding the tile to the name of the images should solve the problem, but I don't know how to do it. 

Just to make it clearer, two files in my local disk are called "S2A_L2A_20171002-113001_**T29SMC**.tif" and "S2A_L2A_20171002-113001_**T29SMD**.tif" (note the different tiles in bold), and they both are renamed as "20171002-113001" in the image collection created with `create_image_collection`. I'd like to have control on the way images are called in the collection.

Hope this is not too confusing
Hugo

**Comment by appelmar** [comment]
The name of images is controlled by the following regular expression in the collection format JSON file:

```
"images" : {
    "pattern" : ".*/(.+)\\.SAFE.*"
}
```
Everything between the round brackets goes into the image name. Based on your example filename, would  `"pattern" : ".*(S2A_L2A.+)\\.tif"` work?

**Comment by lbusett** [comment]
@appelmar 

 I was also trying to build a custom collection format a couple of weeks ago, and was not sure about how the JSON file should be "organized", what the regexes should match to, etcetera.  Is there any references I can look at ? Alternatively, would you consider writing a brief README or something about that ? I think it would really benefit users!

PS: thanks for developing the package! Seems really great!

**Comment by appelmar** [comment]
Thanks for the feedback @lbusett, the JSON format is indeed mostly undocumented. I am currently rewriting some documentation anyway (for GitHub pages) and will add a page on writing custom collection formats there. I'll post the link in this issue.

**Comment by hagc** [comment]
Thank you very much @appelmar 
your suggestion, `".*(S2A_L2A.+)\\.tif"` partially works. I had to add `[AB]`, which is just a detail, to make it `".*(S2[AB]_L2A.+)\\.tif"`, but the problem is that `create_image_collection` now identifies every single band as an individual image.

To be honest, the problem starts with my particular collection, and organized in a strange way as compared to original Landsat or Sentinel data. That said, every tile is found in a dedicated folder, which includes 

1. a TIF file with all bands stacked (but I'm not trying to address this particularity now), and
2. another folder with 3 spectral indices related to each multispectral image:

For now I'm considering the multi-layer TIF as a band, so I was hoping that `create_image_collection` could find the images and 4 bands: "MultiSpectral", "NDVI", "NDMI", and "NDWI".

For example, in this particular tile, I have 106 images, which makes 106*4=424 TIF files. All of the files are considered as images, rather than 106 only:

> A GDAL image collection object, referencing 424 images with 4  bands
> Images:
>                                  name      left      top   bottom     right            datetime                                                srs
> 1 S2A_L2A_20171002-113001_T29SMC_NDMI -10.15275 38.84894 37.85395 -8.887526 2017-10-02T11:30:01 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
> 2 S2A_L2A_20171002-113001_T29SMC_NDVI -10.15275 38.84894 37.85395 -8.887526 2017-10-02T11:30:01 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
> 3 S2A_L2A_20171002-113001_T29SMC_NDWI -10.15275 38.84894 37.85395 -8.887526 2017-10-02T11:30:01 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
> 4 S2A_L2A_20171005-113316_T29SMC_NDMI -10.15275 38.84894 37.85395 -8.887526 2017-10-05T11:33:16 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
> 5 S2A_L2A_20171005-113316_T29SMC_NDVI -10.15275 38.84894 37.85395 -8.887526 2017-10-05T11:33:16 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
> 6 S2A_L2A_20171005-113316_T29SMC_NDWI -10.15275 38.84894 37.85395 -8.887526 2017-10-05T11:33:16 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
> [ omitted 418 images ] 
> 
> Bands:
>            name offset scale unit nodata image_count
> 1 MultiSpectral      0     1                     106
> 2          NDMI      0     1                     106
> 3          NDVI      0     1                     106
> 4          NDWI      0     1                     106

My JSON file looks like this:
```
{
  "description" : "Image collection format for Sentinel 2 L2A data as downloaded from Theia and processed with DGTsentinel2.",
  "tags" : ["Sentinel", "ESA", "Flat Reflectance", "Theia"],
  "pattern" : ".+S2[AB]_L2A.+\\.tif",
  "images" : {
    "pattern" : ".*(S2[AB]_L2A.+)\\.tif"
  },
  "datetime" : {
    "pattern" : ".*/S2[AB]_L2A_([0-9]{8}-[0-9]{6})_.*",
    "format" : "%Y%m%d-%H%M%S"
  },
  "bands" : {
    "MultiSpectral" : {
	  "pattern" : ".+_T29[A-Z]{3}.tif"
	},
	"NDVI" : {
      "pattern" : ".+_T29[A-Z]{3}_NDVI\\.tif"
    },
	"NDMI" : {
      "pattern" : ".+_T29[A-Z]{3}_NDMI\\.tif"
    },
	"NDWI" : {
      "pattern" : ".+_T29[A-Z]{3}_NDWI\\.tif"
    }
  }
}
```

**Comment by appelmar** [comment]
I see two problems with the JSON file:

1. Only the first band of the multispectral file is considered. This can be addressed be splitting the multispectral band up into individual bands where data come from the same file (but different bands):

```
"B01" : {
     "pattern" : ".+_T29[A-Z]{3}.tif",
     "band" : 1
},
"B02" : {
     "pattern" : ".+_T29[A-Z]{3}.tif",
     "band" : 2
},
 ...   
```

2. The four files of one image are interpreted as four individual images. I think a different image pattern in the JSON could also handle your collection, by adding an optional match for "_NDVI", "_NDMI", or "_NDWI" outside the image name part in the regexp. Without testing, could you try the expression below?

```
"images" : {
    "pattern" : ".*(S2[AB]_L2A.+?)(?:_NDVI|_NDMI|_NDWI)?\\.tif"
  }
```

**Comment by appelmar** [comment]
I've managed to rewrite some documentation, including a page about collection formats (see https://gdalcubes.github.io/docs/collection_formats.html). Hope this is helpful.
