### ISSUE TITLE
Custom collection format: several nodata

### ISSUE THREAD

**Issue by liuyadong** [appelmar/gdalcubes_R#20]
Hi, thanks for your amazing work!

Is there a way to define the collection format for dataset like [MOD15A2H](https://lpdaac.usgs.gov/products/mod15a2hv006/) which have several fill values?

**Comment by appelmar** [comment]
Thanks @liuyadong, there is currently no support for several fill values. Not sure, whether this works for your case, but if you simply want to ignore these values, maybe there is an alternative using the actual data band (e.g. "Lai_500m") as an image mask:

```
#x = image_collection(...)
#v = cube_view(...)
z = raster_cube(image_collection(x, v, mask = image_mask("Lai_500m", values=249:255)) 
```

_(This doesn't work with the current CRAN version of the package.)_

If you need both "Fpar_500m" and "Lai_500m" in one data cube, I would create two separate cubes (with different masks) first and then try to combine with `join_bands()`. 

Does this help?

**Comment by liuyadong** [comment]
Thanks for your suggestion. I think it works. Btw, "Fpar_500m" and "Lai_500m" have the same mask, but are different from others.

**Comment by appelmar** [comment]
Interesting dataset, thanks for sharing. It might make sense to support this in the collection format too, but I am not sure how many datasets with several fill values there are. I'll close this issue for now, but feel free to reopen if you have any further ideas or questions.
