### ISSUE TITLE
package update on Debian 10 (stable) 

### ISSUE THREAD

**Issue by paulauvirage** [appelmar/gdalcubes_R#23]
Hello

I have previously successfully installed the package on Debian 10, after installing the recommended Linux packages. The prompted update via R Studio tody came up with the install error

unable to load shared object '/home/paul/R/x86_64-pc-linux-gnu-library/3.6/ncdf4/libs/ncdf4.so':
  libnetcdf.so.11: cannot open shared object file: No such file or directory

I tried an install via R CMD INSTALL in case it was an R Studio issue, but got the same error.

I'm not a sufficiently experienced Linus user to know whether this is a package version problem (Debian 10 uses libnetcdf13, not 11) or path problem.

**Comment by appelmar** [comment]
That looks like a problem with your `ncdf4` package installation, could you try to reinstall with `install.packages("ncdf4")`?

**Comment by paulauvirage** [comment]
Apologies for the slow response. Yes, I uninstalled then reinstalled the `ncdf4` packages, then installation of `gdalcubes` was fine. Thanks.
