### ISSUE TITLE
Query cube with trajectory?

### ISSUE THREAD

**Issue by jskontorp** [appelmar/gdalcubes_R#26]
Hi!

Got a question in relation to a masters thesis in progress for which we are using spatio-temporal data by merging of weather data (NetCDF file from Copernicus Climate Data Store) and marine traffic ship movements (AIS). We want to examine the effect of weather on insurance claims (can add more details if interested).

We were wondering if it might be possible to query a cube with a trajectory object as done below. Suspect this might work better and faster with gdalcubes than our current solution. 

We want to append a few specific meteorological variables (wind, wave height, etc.) to a dataframe containing ship locations and timestamps. We can do a simple query as shown below of one meteorological variable in an STFDF space-time object for part of a single ship's AIS path. However, our real problem is that we have five years of intra-day weather data on several variables to associate with the paths of many ships. The ships are associated with event status in addition, but to study the event status, we need to query the met. cubes to add weather covariates for each point and time in the AIS record (or maybe thinned observations).

The met. data NetCDF files are rather large, so using a proxy mechanism seemed attractive, hence interest in **gdalcubes**. However, we can't see how to query a gdalcubes object not in memory with a path/trajectory object. Our example has everything in memory, which will mean doing things manually in small chunks. Do you have any suggestions?

Example with **spacetime**:

[NetCDF_Query.zip](https://github.com/appelmar/gdalcubes_R/files/3657533/NetCDF_Query.zip) (containing R script, ais data, meteorological data and map plot)

We downloded the met. data from [Copernicus](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form), while the AIS data was provided by a marine insurance company. Attached you can find two sample files used to create the **spacetime** example, as well as the same script as shown below. @rsbivand suggested that we might raise this issue as it may have more general interest.

```
library(sp)
library(spacetime)
library(raster)
library(mapview)
```

First the weather data is loaded using raster::brick with a NetCDF (containing "significant wave height" and "mean wave period") file as input. The brick object is processed into a STFDF object. In this example, only "significant wave height" ("swh") is in focus.
```
brick <- raster::brick(paste0(getwd(), "/weather_sample.nc"), varname = "swh") # "swh" is "significant wave height". Could alternatively load other meteorological varables

sbrick <- as(brick, "SpatialGridDataFrame")
spix <- as(sbrick, "SpatialPixels")
nms <- names(sbrick)
tms <- as.POSIXct(substr(nms, 2, 20), format="%Y.%m.%d.%H.%M.%S", tz="UTC")
prod(gridparameters(spix)$cells.dim)*length(tms) # checks dimensions
dt <- stack(slot(sbrick, "data"))[,1, drop=FALSE]
stfdf <- STFDF(spix, tms, data=dt)
nrow(dt) # checks dimensions

rm(sbrick)
rm(dt)
gc()
```

Marine traffic AIS data (`VESSEL_UID` `LATITUDE`, `LONGITUDE`, `TIME`) is loaded and processed into a STI object (trajectory/path)
```
ais <- read.csv(paste0(getwd(), "/ais_sample.csv"))
ais_df <- ais
coordinates(ais) <- c("LONGITUDE", "LATITUDE")
proj4string(ais) <- CRS(proj4string(spix))
ais$time <- as.POSIXct(as.character(ais$TIME), tz="UTC")
ais_one_ship <- ais[1:30,] # cuts the sample down to 30 first AIS reports
ais.sti <-  STI(ais_one_ship, ais_one_ship$time)
```

The STFDF with the weather data is queried with the trajectory from the AIS data, storing the results in the spatial points data frame
```
res <- over(ais.sti, stfdf)
ais_one_ship$res_swh <- res$values # saves the spatio-temporal specific meteorological data for every line AIS report
```

Note that there will be some NA's as the weather data is based on a .5 degrees grid and rounding of certain values will give positions on land with no recording. Weather data are on a 12-hour basis (6 am, 6 pm), so oversampling/unexpected output will occur (will be dealt with later).
```
ais_view <- as.data.frame(ais_one_ship)[,c(2:5, 7)]
# mapview(ais_one_ship, "res_swh") # .png file in 'query.zip'
```
![map](https://user-images.githubusercontent.com/46783540/65685234-d61a2d00-e061-11e9-9fae-4d192d11836d.png)

Together with @tonneslode
Might be of interest to @basille

**Comment by appelmar** [comment]
Thanks for this issue (and reproducible example). In the current version, I don't think gdalcubes will help you much. There is no point extraction function at the moment, though it's already on my "future development" list, since this is also highly needed e.g. to train machine learning models. 

I am not sure whether this really runs out-of-core, but maybe using `raster::extract()` on the  `brick` object would be an alternative, without using the `spacetime` package and loading everything to main memory?

**Comment by rsbivand** [comment]
Thanks, Marius. The problem is that multiple bands are needed, so array/cube rather than brick. An annual netcdf file at 0.5 degrees with multiple bands is 7GB, and there are 5 years, so 35GB roughly. It may well be that 0.5 degrees is too coarse near coasts too. **spacetime** matched better because the actual space-time points are often between brick time slices, and I don't know how extract interpolates on the time dimension. Maybe this is rather a **stars** array question with a trajectory query @edzer - by the was a nice case for NY?

**Comment by jskontorp** [comment]
Thanks for your reply, Marius. 

All right, good to know. We have tried using `raster::extract()` on time slices of the `brick` object but it works fairly slow on another small sample with about 800 AIS observations recorded every twelve hours for which we have met. data (and we are looking at hundreds of thousands). So, as Rorger says, it might be difficult.

On a side note, it seems that we can solve our problem by using `ncdf4::ncvar_get()` with `dplyr::mutate()` to extract the met. data variables for every observation in our AIS dataframe. It works really fast gathering and appending tens of thousands of met. data variables to our dataframe in seconds. Here we are of course not using any spatial or spatio-temporal points at all, and roundings and interpolations are done manually.

**Comment by mdsumner** [comment]
@jskontorp  We do this routinely with [raadtools](http://australianantarcticdivision.github.io/raadtools/reference/extract.html) (we extend `raster::extract` with a method on *function,dataframe*, it's relatively easy to run our function if you have a read_x function of time, but given the history of how we got there it also needs some way of getting a sensible file list (in a data frame), and an escape hatch argument "returnfiles". Usually for us the hard part to share is the access to the time series of files, but I'd be happy to work through this if you like.

**Comment by mdsumner** [comment]
@jskontorp thanks for the example, I got quite a way through it but there's still more to do, ultimately I'd like to abstract this out of our institutional set-up and maybe there's something to share:  https://github.com/AustralianAntarcticDivision/raadtools/issues/97
