### ISSUE TITLE
installation of github version fails

### ISSUE THREAD

**Issue by hewag1975** [appelmar/gdalcubes_R#59]
Hi Marius,
installing the github version with `remotes::install_git("https://github.com/appelmar/gdalcubes_R")` fails for me throwing:
```
make: *** No rule to make target 'gdalcubes/src/aggregate_time.o', needed by 'gdalcubes.so'.  Stop.
ERROR: compilation failed for package ‘gdalcubes’
```
I checked the system libraries, but they seem to be all up-to-date:
```
~$ sudo apt-get install libgdal-dev libnetcdf-dev libcurl4-openssl-dev libsqlite3-dev libudunits2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnetcdf-dev is already the newest version (1:4.7.3-1).
libudunits2-dev is already the newest version (2.2.26-5).
libcurl4-openssl-dev is already the newest version (7.68.0-1ubuntu2.7).
libsqlite3-dev is already the newest version (3.31.1-4ubuntu0.2).
libgdal-dev is already the newest version (3.4.0+dfsg-1~focal0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
Any idea what's going wrong here?
Best, Hendrik

**Comment by appelmar** [comment]
Hi, pretty sure it is not cloning the git submodule and the `src/gdalcubes` directory is empty. Can you try the following in the command line?

```
git clone --recursive https://github.com/appelmar/gdalcubes_R
cd gdalcubes_R
R CMD INSTALL .
```

The "--recursive" option is important here. Some time ago, `remotes::install_git()` had an `args` argument to add git options but that seems to be not available anymore.

**Comment by hewag1975** [comment]
Yes, can confirm that this works. Not sure if there is a better option?

**Comment by appelmar** [comment]
Thanks! For sure, as far as I understand, `remotes::install_git()` should automatically clone the submodule, too, but I need some more time to find out what is going wrong.

**Comment by appelmar** [comment]
Turned out that `remotes` ignored the submodule due to two empty lines at the end of `.Rbuildignore`, so it should work now with `remotes::install_git("https://github.com/appelmar/gdalcubes_R")`, too. Thanks again for raising this issue.

**Comment by hewag1975** [comment]
Yes, can confirm that this works. Thanks!
