### ISSUE TITLE
Collection projection system in "proj:wkt2" attribute not supported

### ISSUE THREAD

**Issue by SarahVal** [appelmar/gdalcubes_R#60]
Hi ! 
We encountered issues when loading a collection from a stac path, and for which the projection system is stored in WKT format, in the attribute"proj:wkt2":... (the attribute "proj:epsg" is null.) With this collection, it seems that the use of a new projection system in the function cube_view is not supported thus resulting in an incorrect cube cropping.
Thanks for helping !
Sarah

**Comment by appelmar** [comment]
Thanks for the issue! I think it should work now if you install the package from GitHub, although I could not test. Please let me know if there are still problems.

**Comment by appelmar** [comment]
Is it a public STAC catalog that I can use for testing?

**Comment by glaroc** [comment]
There seems to be an issue with the way the functions are exported in the current version on Github. After installation

**Comment by appelmar** [comment]
Oops, sorry, NAMESPACE was broken, does it work now?

**Comment by glaroc** [comment]
Installation works and I believe the proj:wkt2 works as well!

**Comment by appelmar** [comment]
Thanks for checking, I'll close the issue for now. Feel free to re-open if anything does not work.

**Comment by glaroc** [comment]
@appelmar is it possible that extract_geom() won't work if the source raster data in the STAC collection that forms the cube has a projection defined with proj:wkt2 ? I'm trying to debug extraction from one of our datasets and I feel that this might be the issue.

**Comment by appelmar** [comment]
Sounds rather unlikely to me, can you share some more details (e.g. image collection file, scripts or debug output)?

**Comment by glaroc** [comment]
Upon further testing, I believe the issue was that the structure of that collection in our Stac catalog didn't fit with the expected structure of extract_geom(). I changed the order of operations and now it works with proj:wkt2 definition.

**Comment by appelmar** [comment]
OK, thanks for the update, there is a small chance that this is also related to the apostrophe issue (#70), if the WKT contains single quotes.
