### ISSUE TITLE
Apostrophe in properties breaks stac_image_collection()

### ISSUE THREAD

**Issue by glaroc** [appelmar/gdalcubes_R#70]
We had a properties.description in our STAC catalog with apostrophes and it broke stac_image_collection() call. 

````
[ERROR] Failed to insert image metadata into image collection database
Error in gc_create_stac_collection(bands_df, images_df, gdalrefs_df, path.expand(out_file),  : 
  Failed to insert image metadata into image collection database
````
We simply fixed it by changing the description to remove the apostrophes, but this might be an issue especially for non-English catalogues.

**Comment by appelmar** [comment]
Thanks, very important for other languages indeed. This should now work with https://github.com/appelmar/gdalcubes/pull/51/commits/baee858354ccc8851916a96a1cdd70ce47fdfa65. Single-quotes are now escaped according to https://www.sqlite.org/faq.html#q14. I've done some tests with artificially added apostrophes and random Unicode characters and had no issues, so I'll close the issue for now.
