### ISSUE TITLE
unexpected errors in stac_image_collection

### ISSUE THREAD

**Issue by cboettig** [appelmar/gdalcubes_R#71]
Thanks for this amazing package, the ability to create a virtual cube directly from a STAC search seems very powerful.  Unfortunately I'm having a bit of trouble with the following example, but cannot spot where stac_image_collection() is getting snagged up.  

```r
library(rstac)
library(gdalcubes)
box <- c(xmin=-122.51006, ymin=37.70801, xmax=-122.36268, ymax=37.80668) 

matches <-
  stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "modis-15A2H-061",
              datetime = "2022-11-01/2022-11-08",
              bbox = c(box),
              limit = 10) |>
  get_request() |>
  items_fetch() |>
  items_sign(sign_fn = sign_planetary_computer())
#matches |> assets_select("Lai_500m") |> gdalcubes::stac_image_collection()
cube <- gdalcubes::stac_image_collection(matches$features, asset_names = "Lai_500m")
```

**Comment by appelmar** [comment]
Thanks, it seems  that instead of `datetime`,  the returned STAC items contain `start_endtime` and `end_datetime` properties, while `stac_image_collection()` expects the former.
The following workaround works for me:

```
features_new = lapply(matches$features, function(x) {
  x$properties$datetime = x$properties$start_datetime
  return(x)
})

cube <- gdalcubes::stac_image_collection(features_new, asset_names = "Lai_500m")
cube
```

Not sure if this is compliant with the STAC specification. To me it seems that `datetime` is required (see https://github.com/radiantearth/stac-spec/blob/fd8fb4e3cf0b6c4a0fe74822accbc1725a92f92a/item-spec/json-schema/item.json#L136). Can you help, @m-mohr?

**Comment by m-mohr** [comment]
`datetime` is allowed to be null if `start_datetime` and `end_datetime` are given. If a single datetime is required, people sometimes compute a center datetime or just use the start_datetime.

https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#datetime

**Comment by appelmar** [comment]
Great, thanks for clarifying! I'll adapt `stac_image_collection()` accordingly. However, adding full support for images with datetime intervals when creating data cubes (other than just using the start / center datetime) might need some additional work.

**Comment by cboettig** [comment]
Thanks both!  @appelmar I think it would be fine to fill with the center datetime or start_datetime in most cases.  Maybe an optional argument to toggle this, something like `duration = c("start", "center", NA)` perhaps?

**Comment by appelmar** [comment]
Thanks for the suggestion, this is now implemented with default being "center".

**Comment by cboettig** [comment]
awesome!  Works great, thanks.
