### ISSUE TITLE
Warn if GDAL 3.6.0 used

### ISSUE THREAD

**Issue by rsbivand** [appelmar/gdalcubes_R#77]
See https://github.com/r-spatial/sf/issues/2077, https://github.com/rspatial/terra/issues/965, https://github.com/hypertidy/vapour/issues/183 for this problem.

Further, Rtools43 has been announced: https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html and getting **gdalcubes** away from R-Winlib is important now, as R 4.2 will be oldrel when 4.3 is released in April. You'll need a custom `src/Makevars.ucrt` possibly extending that of **sf**, **terra** or **vapour**. You could try those first. Rtools 40 uses a different compiler etc., from 42 and now 43, and mixing 40-built external static libraries in building gdalcubes.dll using 42 or 43 is likely to cause transient errors at some point.

**Comment by rsbivand** [comment]
Maybe:
```
AC_MSG_CHECKING([GDAL version != 3.6.0])
if test ${GDAL_MAJOR} = 3 && test ${GDAL_MINOR} = 6 && test ${GDAL_PATCH} = 0 ; then
  AC_MSG_RESULT(no)
  AC_MSG_ERROR([GDAL 3.6.0 was retracted, use a subsequent version])
else
  AC_MSG_RESULT(yes)
fi
```
will be best?

**Comment by appelmar** [comment]
Thanks a lot! I took your suggested GDAL 3.6.0 test and added a Makevars.ucrt file based on `sf`, which seems to work fine on r-devel win-builder. I'll do some more tests and prepare a  CRAN submission soon.
