### ISSUE TITLE
Custom collection format: add correction value and different types of images

### ISSUE THREAD

**Issue by norival** [appelmar/gdalcubes_R#8]
Hi, and thank you for your work on gdalcubes :)

I'm trying to create a custom collection format for Sentinel2 data as provided by Theia (https://theia.cnes.fr). It seems to work. But, is there a way to specify the correction value that needs to be applied to the data? (the data needs to be divided by 10000 to get the reflectance value).

Also, this data contains a subdirectory named 'MASKS', which contains masks for clouds, saturated pixels, and others (for 10 and 20 m resolutions). Is there a way to specify them in the collection format?

**Comment by appelmar** [comment]
Hi,

gdalcubes tries to read the scale and offset values from the GDAL metadata by calling ` GDALRasterBand::GetScale()` and `GDALRasterBand::GetOffset()`. There is currently no way to define per-band metadata in the collection format (except nodata values), but this would indeed be nice to have. AFAICS this should be easy to add, my suggestion would be to add something like this to 
the band definition in the collection format:

```
...
"B02" : {
      "nodata" : 0,
      "pattern" : ".+_B02_10m\\.jp2"
      "scale" : 10000
      "offset" : 0
      "unit" : "..."
    }
...
```

Including the masks should be possible by adding them as regular bands in the collection format. There is  some experimental support for applying masks in the `dev` branch, where the `raster_cube` function got a new argument `image_mask`. There is also an updated Sentinel 2 L2A collection format including SCL, AOT, and WVP bands for the original SAFE format (see [here](https://github.com/appelmar/gdalcubes_formats/blob/master/formats/Sentinel2_L2A.json)), maybe this helps?

**Comment by norival** [comment]
Hi, thank you very much for your help!

It could be nice indeed, scale value does not seem to be read from this dataset.

I managed to add the masks as regular bands, as you suggested. I also tried the mask support from the `dev` branch, and everything seems to be ok, thanks a lot :)

**Comment by hagc** [comment]
Dear both
could I ask you to share with me this json file (for Sentinel-2 data downloaded from Theia)? I'm struggling with it and facing problems... 
It would be also very nice to have it in the next realise of the package, if I may suggest.
Thank you very much
Hugo

**Comment by norival** [comment]
Hi @hagc, you can find a copy of this file here:

https://github.com/norival/theiaR/blob/devel/inst/templates/gdalcubes_theia.json

I used it a bit and it seems to work fine. I hope it can help you :)

Xavier

**Comment by hagc** [comment]
Thank you very much. Very kind of you.
Hugo

**Comment by appelmar** [comment]
Thanks for sharing @norival! Scale, offset, and unit values are also read from the collection format now (see 8acf19511eca30c6ae2b9c0ec327f962eab23500).
