### ISSUE TITLE
Mac OS X package installation on CRAN 

### ISSUE THREAD

**Issue by appelmar** [appelmar/gdalcubes_R#9]
Resubmitted the package to CRAN. Since it was rejected before due to Mac OS X installation failure, the configure script now uses the recipe from rgdal to link to GDAL and PROJ. 

@s-u @edzer The packages [sf](https://cran.r-project.org/web/packages/sf/index.html) and [rgdal](https://cran.r-project.org/web/packages/rgdal/index.html) have custom configure flags for Mac OS X builds (see https://svn.r-project.org/R-dev-web/trunk/QA/Simon/packages/flags.inst/). Since the gdalcubes package also links to GDAL, would these flags be needed to build MacOS X binaries on CRAN as well?

**Comment by edzer** [comment]
CRAN package [landsepi](https://cran.r-project.org/web/packages/landsepi/index.html) also builds against GDAL, has osx binaries, but does not have the build flag in place. Mabye because it doesn't need to copy the configuration files? Does gdalcubes need those?

**Comment by appelmar** [comment]
CRAN no successfully builds on Mac OS X (see https://cran.r-project.org/web/checks/check_results_gdalcubes.html)

**Comment by edzer** [comment]
Can you try with a netcdf3 instead of netcdf4 dataset? We had the same issue with stars, there that helped. Or you could make the test platform dependent.

**Comment by appelmar** [comment]
It does work for Mac OS X, only Solaris fails so far (see #15). This indeed seems to be caused by netcdf4 files created by gdalcubes.
